// Generated by gencpp from file gcv_motor_driver/GCVControl.msg
// DO NOT EDIT!


#ifndef GCV_MOTOR_DRIVER_MESSAGE_GCVCONTROL_H
#define GCV_MOTOR_DRIVER_MESSAGE_GCVCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gcv_motor_driver
{
template <class ContainerAllocator>
struct GCVControl_
{
  typedef GCVControl_<ContainerAllocator> Type;

  GCVControl_()
    : header()
    , left_track(0.0)
    , right_track(0.0)  {
    }
  GCVControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_track(0.0)
    , right_track(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_track_type;
  _left_track_type left_track;

   typedef float _right_track_type;
  _right_track_type right_track;




  typedef boost::shared_ptr< ::gcv_motor_driver::GCVControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gcv_motor_driver::GCVControl_<ContainerAllocator> const> ConstPtr;

}; // struct GCVControl_

typedef ::gcv_motor_driver::GCVControl_<std::allocator<void> > GCVControl;

typedef boost::shared_ptr< ::gcv_motor_driver::GCVControl > GCVControlPtr;
typedef boost::shared_ptr< ::gcv_motor_driver::GCVControl const> GCVControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gcv_motor_driver::GCVControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gcv_motor_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gcv_motor_driver': ['/home/edf/ROS/edf/catkin_ws/src/gcv_motor_driver/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gcv_motor_driver::GCVControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcv_motor_driver::GCVControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcv_motor_driver::GCVControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2e51d95c55716bb1993b7d66b71eb5a";
  }

  static const char* value(const ::gcv_motor_driver::GCVControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2e51d95c55716bbULL;
  static const uint64_t static_value2 = 0x1993b7d66b71eb5aULL;
};

template<class ContainerAllocator>
struct DataType< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gcv_motor_driver/GCVControl";
  }

  static const char* value(const ::gcv_motor_driver::GCVControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 left_track\n\
float32 right_track\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gcv_motor_driver::GCVControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_track);
      stream.next(m.right_track);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GCVControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gcv_motor_driver::GCVControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gcv_motor_driver::GCVControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_track: ";
    Printer<float>::stream(s, indent + "  ", v.left_track);
    s << indent << "right_track: ";
    Printer<float>::stream(s, indent + "  ", v.right_track);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GCV_MOTOR_DRIVER_MESSAGE_GCVCONTROL_H
